'use client';

const Rings = () => {
    return(
        <div 
            className="
                absolute 
                top-1/2 
                left-1/2
                w-[48rem] 
                aspect-square 
                border 
                border-bg-light  
                rounded-full 
                -translate-x-1/2 
                -translate-y-1/2
            "
        >
            <div 
                className="
                    absolute 
                    top-1/2 
                    left-1/2 
                    w-4 
                    aspect-square 
                    border 
                    border-bg-light
                    rounded-full 
                    -translate-x-1/2 
                    -translate-y-1/2
                " 
            />
            <div 
                className="
                    absolute 
                    top-1/2 
                    left-1/2 
                    w-48
                    aspect-square 
                    border 
                    border-bg-light
                    rounded-full 
                    -translate-x-1/2 
                    -translate-y-1/2
                " 
            />
            <div 
                className="
                    absolute 
                    top-1/2 
                    left-1/2 
                    w-96
                    aspect-square 
                    border 
                    border-bg-light
                    rounded-full
                    -translate-x-1/2 
                    -translate-y-1/2
                " 
            />
            <div 
                className="
                    absolute 
                    top-1/2 
                    left-1/2 
                    w-[36rem]
                    aspect-square 
                    border 
                    border-bg-light
                    rounded-full
                    -translate-x-1/2 
                    -translate-y-1/2
                " 
            />
        </div>
    )
}

export default Rings;